### PR TITLE
Add example file link to the plugin page

### PR DESCRIPTION
**Pull request by phy25**
The new link is below the upload button and it is translatable. Adding this may help users to create the CSV file instantly.

### CODE REVIEW

**Comment by sorich87** [comment]
Please, can you send another pull request where the formatting of import-users-from-csv.php is not changed?
I am not able to see the changes in this diff.

**Comment by phy25** [comment]
That's OK. Please check out the request.

**Comment by phy25** [comment]
@sorich87 the new commit is included in this pull request now

**Comment by sorich87** [comment]
Yes, I saw it. Thanks!

I would like to wrap the new text in a <span class="description">, just to follow WordPress admin UI convention.
You can do it and resend the request, or I will do it later.

**Comment by phy25** [comment]
I am sorry that the document type changed unexpectedly again. It's OK now.

**Comment by sorich87** [comment]
No problem. Thanks! :)

**Pull request merged**
